// SCENA — props: the prop library
//
// A sub-path entry point. `import from 'scena3d'` still gives you everything;
// this exists so a bundler can see module boundaries, and so an import says
// what part of the library it depends on.
//
// GENERATED from src/index.ts by scripts/entries.mjs — every statement below
// is the root barrel's own, partitioned by source directory. `npm run
// entries:check` fails if this file and the barrel disagree.

export {
  createTree,
  treeBiome,
  TREE_SPECIES,
  TREE_BIOMES,
  type TreeOptions,
  type TreeSpecies,
  type TreeSeason,
  type TreeBiome,
  type TreeBiomeOptions,
} from './props/tree';
export {
  createImpostor,
  treeLOD,
  type ImpostorOptions,
  type ImpostorProfile,
  type TreeLODOptions,
} from './props/impostor';
export { createRock, type RockOptions } from './props/rock';
export { createCrate, type CrateOptions } from './props/crate';
export {
  createBarrel,
  createBasket,
  createSack,
  createLantern,
  type CarryableOptions,
  type LanternOptions,
} from './props/carryables';
export {
  createChoppingBlock,
  createOreVein,
  createCookpot,
  createSawhorse,
  type WorkStation,
  type WorkStationOptions,
} from './props/workstations';
export { createFence, type FenceOptions } from './props/fence';
export { createLamp, type LampOptions } from './props/lamp';
export { createGrassTuft, createBush, type GrassOptions, type BushOptions } from './props/grass';
export {
  createHouse,
  createTower,
  createWell,
  createRuin,
  type HouseOptions,
  type TowerOptions,
  type WellOptions,
  type RuinOptions,
  type WallStyle,
  type RoofStyle,
} from './props/building';
export { createStall, type StallOptions, type StallGoods } from './props/stall';
export {
  createBanner,
  type BannerOptions,
  type BannerStyle,
  type BannerPattern,
} from './props/banner';
export { createBrazier, createCampfire, type FireOptions } from './props/fire';
export {
  createTable,
  createSeat,
  createBed,
  createShelf,
  createChest,
  createCandle,
  createRug,
  type TableOptions,
  type TableStyle,
  type SeatOptions,
  type SeatStyle,
  type BedOptions,
  type BedSize,
  type ShelfOptions,
  type ShelfStock,
  type ChestOptions,
  type CandleOptions,
  type CandleStyle,
  type RugOptions,
  type RugShape,
} from './props/furniture';
export {
  createDiningTable,
  createPicnicTable,
  createLongBench,
  createGameTable,
  createCampCircle,
  type GatheringOptions,
  type DiningTableOptions,
  type PicnicTableOptions,
  type LongBenchOptions,
  type GameTableOptions,
  type CampCircleOptions,
  type BoardGame,
} from './props/gatherings';
export { createBunting, type BuntingOptions } from './props/bunting';
export { createFountain, type FountainOptions } from './props/fountain';
export {
  createCart,
  type CartOptions,
  type CartStyle,
  type CartCargo,
} from './props/cart';
export {
  createStatue,
  type StatueOptions,
  type StatueFigure,
  type StatueMaterial,
} from './props/statue';
export {
  createSign,
  type SignOptions,
  type SignKind,
  type Direction,
} from './props/sign';
export {
  createPlane,
  createHelicopter,
  createFighterJet,
  type AircraftProp,
  type AircraftInput,
  type PlaneOptions,
  type HelicopterProp,
  type HelicopterInput,
  type HelicopterOptions,
  type FighterProp,
  type FighterInput,
  type FighterOptions,
} from './props/aircraft';
export {
  createRunway,
  createWindsock,
  createHangar,
  createHelipad,
  type Runway,
  type RunwayOptions,
  type Windsock,
  type WindsockOptions,
  type HangarOptions,
  type HelipadOptions,
} from './props/airfield';
export {
  createStreetLight,
  createLanternLight,
  createNeonSign,
  createStringLights,
  createRevolvingBeacon,
  createPhotocell,
  type Luminous,
  type LuminousClaim,
  type StreetLightOptions,
  type LanternLightOptions,
  type NeonSign,
  type NeonSignOptions,
  type StringLightsOptions,
  type RevolvingBeaconOptions,
  type Photocell,
  type PhotocellOptions,
} from './props/luminous';
export {
  createPickup,
  createPickupField,
  type Pickup,
  type PickupKind,
  type PickupState,
  type PickupOptions,
  type PickupField,
  type PickupFieldOptions,
  type FieldTrigger,
} from './props/pickups';
export {
  createCheckpoint,
  createZone,
  createBeacon,
  createFinishGate,
  type Checkpoint,
  type CheckpointState,
  type CheckpointOptions,
  type Zone,
  type ZoneOptions,
  type Beacon,
  type BeaconOptions,
  type FinishGate,
  type FinishGateOptions,
} from './props/markers';
export {
  createPlatform,
  createCrumblingPlatform,
  createBouncePad,
  createPendulum,
  createSpikeTrap,
  createConveyor,
  createPressurePlate,
  type MovingPlatform,
  type PlatformOptions,
  type PlatformMotion,
  type CrumblingPlatform,
  type CrumbleOptions,
  type CrumbleState,
  type BouncePad,
  type BouncePadOptions,
  type Pendulum,
  type PendulumOptions,
  type SpikeTrap,
  type SpikeTrapOptions,
  type Conveyor,
  type ConveyorOptions,
  type PressurePlate,
  type PressurePlateOptions,
} from './props/hazards';
export {
  createBreakable,
  createTargetDummy,
  createScoreboard,
  createStumps,
  type Breakable,
  type BreakableKind,
  type BreakableState,
  type BreakableOptions,
  type TargetDummy,
  type TargetDummyOptions,
  type Scoreboard,
  type ScoreboardOptions,
  type Stumps,
  type StumpsOptions,
} from './props/destructibles';
export {
  createForge,
  createOven,
  createLoom,
  createCounter,
  type WorkshopOptions,
} from './props/workshop';
export {
  createTreadmill,
  createGuitar,
  createToilet,
  createSink,
  createBathtub,
  type TreadmillOptions,
  type TreadmillProp,
  type GuitarOptions,
  type BathroomOptions,
} from './props/stations';
export {
  createCar,
  createBike,
  createTractor,
  createTruck,
  type VehicleOptions,
  type VehicleInput,
  type VehicleProp,
} from './props/vehicles';
export {
  createBoat,
  createShip,
  type CraftOptions,
  type CraftInput,
  type CraftProp,
} from './props/watercraft';
export {
  createRailing,
  createModernWindow,
  createGate,
  createCladding,
  createPergola,
  createPlanter,
  type RailingOptions,
  type RailingStyle,
  type ModernWindowOptions,
  type ModernWindowStyle,
  type ModernWindowProp,
  type GateOptions,
  type GateStyle,
  type GateProp,
  type CladdingOptions,
  type CladdingStyle,
  type PergolaOptions,
  type PlanterOptions,
} from './props/modern';
export {
  createDoor,
  createDrawer,
  createLever,
  createValve,
  createHatch,
  createPortcullis,
  type Manipulable,
  type MechanismOptions,
  type DoorOptions,
  type DrawerOptions,
  type LeverOptions,
  type ValveOptions,
  type HatchOptions,
  type PortcullisOptions,
} from './props/mechanisms';
export {
  createLadder,
  createSaddle,
  createBridle,
  type Ladder,
  type LadderOptions,
  type LadderStyle,
  type TackOptions,
  type TackStyle,
} from './props/climbing';
export {
  createMonitor,
  createTelevision,
  createLaptop,
  createSmartDisplay,
  createTablet,
  createPhone,
  createSmartwatch,
  createScreenLight,
  type ScreenProp,
  type ScreenPropOptions,
  type ScreenCarryable,
  type TelevisionOptions,
  type LaptopOptions,
  type ScreenLight,
  type ScreenLightOptions,
} from './props/electronics';
export {
  createTerminal,
  type Terminal,
  type TerminalOptions,
  type TerminalStyle,
} from './props/terminals';
export {
  createFixture,
  createDeskSet,
  type Fixture,
  type FixtureOptions,
  type FixtureStyle,
  type DeskSet,
} from './props/fixtures';
export {
  createPainting,
  createFramedPhoto,
  createMirror,
  createWallClock,
  createTapestry,
  type WallArt,
  type FrameStyle,
  type PaintingOptions,
  type FramedPhotoOptions,
  type MirrorOptions,
  type WallClock,
  type WallClockOptions,
  type TapestryOptions,
} from './props/wallArt';
export {
  createShower,
  createTub,
  createJacuzzi,
  type Shower,
  type ShowerOptions,
  type ShowerStyle,
  type ShowerState,
  type Tub,
  type TubOptions,
  type TubStyle,
  type Jacuzzi,
  type JacuzziOptions,
} from './props/bathing';
export {
  createPool,
  type Pool,
  type PoolOptions,
  type PoolStyle,
  type PoolLadder,
} from './props/pool';
export {
  createHeatSource,
  createHearth,
  createRange,
  createHob,
  type HeatSource,
  type HeatOptions,
  type HeatEra,
  type HeatState,
  type HeatZone,
  type HeatControl,
  type HeatField,
} from './props/heat';
export {
  createCookware,
  COOKWARE_KINDS,
  type Cookware,
  type CookwareOptions,
  type CookwareKind,
  type CookState,
} from './props/cookware';
export {
  createPrepStation,
  PREP_KINDS,
  type PrepStation,
  type PrepOptions,
  type PrepKind,
} from './props/prep';
export {
  createSailRig,
  RIG_KINDS,
  noGoDegrees,
  type SailRig,
  type SailOptions,
  type RigKind,
  type WindSource,
} from './props/sail';
export {
  createBerth,
  moor,
  createGangway,
  BERTH_ERAS,
  type Berth,
  type BerthEra,
  type BerthOptions,
  type Bollard,
  type Mooring,
  type MooringLine,
  type MooringOptions,
  type Moorable,
  type Gangway,
  type GangwayOptions,
  type Carrier,
} from './props/mooring';
export {
  createOarBank,
  oarGripAt,
  OAR_KINDS,
  OAR_GRIP,
  type OarBank,
  type OarBankOptions,
  type OarKind,
  type Oar,
} from './props/oars';
export {
  createSteamPlant,
  pressureFor,
  tempFor,
  expansionRatio,
  steamPerWork,
  firesVisibleFrom,
  STEAM_KINDS,
  type SteamPlant,
  type SteamPlantOptions,
  type SteamKind,
  type SteamState,
  type SteamControl,
} from './props/steamPlant';
export {
  createHold,
  freeSurfaceCost,
  holdPoint,
  HOLD_KINDS,
  type Hold,
  type HoldOptions,
  type HoldKind,
  type Compartment,
  type Loading,
  type TrimState,
} from './props/hold';
export {
  createStabilisers,
  dampingAt,
  STABILISER_KINDS,
  type Stabilisers,
  type StabiliserOptions,
  type StabiliserKind,
} from './props/stabiliser';
export {
  createPlumbing,
  headPressure,
  orificeFlow,
  mixedAt,
  mixFor,
  SUPPLY_KINDS,
  SCALD,
  type Plumbing,
  type PlumbingOptions,
  type SupplyKind,
  type SupplyState,
  type OutletKind,
  type OutletOptions,
  type Draw,
} from './props/plumbing';
export {
  createPA,
  spreadingLoss,
  barrierLoss,
  exposureLimit,
  earshot,
  loudnessState,
  sumDecibels,
  AIR_ABSORPTION,
  A_WEIGHTING,
  BAND_HZ,
  BARRIER_CAP,
  SPEED_OF_SOUND,
  QUIET,
  SHOUTING,
  HARMFUL,
  SHOUT_AT_1M,
  type PublicAddress,
  type PAOptions,
  type PAEra,
  type Band,
  type BandLevels,
  type LoudnessState,
  type EchoState,
  type EchoReading,
  type SoundField,
  type SoundArrival,
  type SourceSpec,
  type BarrierSpec,
} from './props/sound';
export {
  createWoofer,
  createDanceTiles,
  bedPulse,
  RADIO_STATIONS,
  type Woofer,
  type WooferOptions,
  type WooferState,
  type RadioStation,
  type RadioMedia,
  type AudioPulse,
  type DanceTiles,
  type DanceTilesOptions,
} from './props/woofer';
export {
  createShala,
  SHALA_ERAS,
  type Shala,
  type ShalaEra,
  type ShalaOptions,
  type MatSpot,
} from './props/shala';
export {
  createSingingBowl,
  type SingingBowl,
  type SingingBowlOptions,
  type BreathPulse,
} from './props/bowl';
export { createBeach, type Beach, type BeachOptions } from './props/beach';
export {
  createCricketGround,
  createBat,
  createCricketBall,
  PITCH_LENGTH,
  PITCH_WIDTH,
  STUMP_HEIGHT,
  STUMP_SPREAD,
  CREASE_FRONT,
  type CricketGround,
  type CricketGroundOptions,
  type CricketBallProp,
  type BatOptions,
} from './props/cricket';
export {
  createPalm,
  createBananaTree,
  type TropicalTree,
  type PalmOptions,
  type BananaOptions,
} from './props/tropics';
export { createLagoon, type Lagoon, type LagoonOptions } from './props/lagoon';
export {
  createLifeguardTower,
  createBeachUmbrella,
  createLounger,
  MIAMI_COLORS,
  type BeachProp,
  type LifeguardTowerOptions,
  type BeachUmbrellaOptions,
  type LoungerOptions,
  type LoungerRecline,
} from './props/beachkit';
export {
  createSeamark,
  geographicRange,
  luminousRange,
  MARK_KINDS,
  SECTOR_TRANSMISSION,
  NM,
  type Seamark,
  type SeamarkOptions,
  type MarkKind,
  type SightState,
  type Sighting,
  type Sector,
} from './props/seamark';
export {
  createSmallCraft,
  livesIn,
  isBreaking,
  CRAFT_FITS,
  type SmallCraft,
  type SmallCraftOptions,
  type CraftFit,
  type CraftState,
  type Hand,
} from './props/smallCraft';
export {
  createGear,
  listFor,
  GEAR_KINDS,
  type Gear,
  type GearOptions,
  type GearKind,
  type GearState,
} from './props/gear';
export {
  createPressureGauge,
  type PressureGauge,
  type PressureGaugeOptions,
} from './props/gauge';
export {
  createDeckedShip,
  SHIP_ERAS,
  type DeckedShip,
  type DeckedShipOptions,
  type ShipEra,
  type ShipInput,
  type DeckField,
  type DeckLevel,
  type Companionway,
} from './props/deckedShip';
export {
  createSmoke,
  createExtractor,
  createSmokeLayer,
  SMOKE_STYLES,
  EXTRACTOR_ERAS,
  type SmokeSource,
  type SmokeOptions,
  type SmokeStyle,
  type SmokeField,
  type Extractor,
  type ExtractorOptions,
  type ExtractorEra,
  type ExtractorFan,
  type SmokeLayer,
  type SmokeLayerOptions,
} from './props/smoke';
export {
  createIngredient,
  keepsFor,
  INGREDIENT_KINDS,
  type Ingredient,
  type IngredientOptions,
  type IngredientKind,
  type IngredientForm,
  type IngredientState,
} from './props/ingredient';
export {
  createDresser,
  stock,
  createUtensil,
  createCrockery,
  createKitchenware,
  DRESSER_KINDS,
  UTENSIL_STYLES,
  type Storage,
  type StorageSpace,
  type SpaceKind,
  /** The prop a dresser returns. Named `Storage` because that is what it is. */
  type DresserKind,
  type DresserOptions,
  type DresserDoor,
  type StockOptions,
  type UtensilStyle,
  type UtensilOptions,
  type CrockeryOptions,
  type KitchenwareOptions,
} from './props/dresser';
export {
  createWashUp,
  createTrough,
  createKitchenSink,
  createDishwasher,
  SINK_ERAS,
  type WashUp,
  type SinkOptions,
  type SinkEra,
  type SinkDoor,
  type WashQueue,
} from './props/sink';
export {
  createColdStore,
  createLarder,
  createIcebox,
  createFridge,
  spoilRate,
  COLD_ERAS,
  type ColdStore,
  type ColdOptions,
  type ColdEra,
  type ColdState,
  type ColdDoor,
  type ChillField,
} from './props/cold';
export {
  createBasin,
  createTap,
  createEwer,
  BASIN_ERAS,
  type Basin,
  type BasinOptions,
  type BasinEra,
  type Tap,
  type TapOptions,
  type TapStyle,
  type EwerOptions,
} from './props/washing';
export {
  createStream,
  createSpray,
  createFill,
  createSteam,
  type Stream,
  type StreamOptions,
  type Spray,
  type SprayOptions,
  type Fill,
  type FillOptions,
  type Steam,
  type SteamOptions,
} from './props/waterworks';
export {
  createPlant,
  createHangingPlant,
  createWindowBox,
  PLANT_SPECIES,
  type Plant,
  type PlantOptions,
  type PlantSpecies,
  type HangingPlantOptions,
  type WindowBoxOptions,
} from './props/plants';
export {
  createCurtains,
  createCushion,
  createThrow,
  type Curtains,
  type CurtainsOptions,
  type CurtainStyle,
  type CushionOptions,
  type ThrowOptions,
} from './props/soft';
export {
  createPoster,
  createPinboard,
  createWhiteboard,
  createStickyNotes,
  type PosterOptions,
  type PinboardOptions,
  type WhiteboardOptions,
  type StickyNotesOptions,
} from './props/paper';
export {
  createVessel,
  VESSEL_STYLES,
  type Vessel,
  type VesselOptions,
  type VesselStyle,
} from './props/vessels';
export {
  createBooks,
  createPapers,
  createFolded,
  createTrinket,
  createFruitBowl,
  createClutter,
  CLUTTER_THEMES,
  type BooksOptions,
  type BookStyle,
  type PapersOptions,
  type FoldedOptions,
  type TrinketOptions,
  type FruitBowlOptions,
  type ClutterOptions,
  type ClutterKitOptions,
  type ClutterTheme,
} from './props/clutter';
